name: Go CLI Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # create a file in the working directory
    - name: Create a file
      run: echo "Hello, World!" > yoooohooooo.txt

    - name: Run Go CLI Test
      uses: radugrecu/go-cli-test@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
